# Generated by Django 4.2.4 on 2023-08-11 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='couponCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ccode', models.CharField(max_length=50)),
                ('expire_date', models.DateField(blank=True)),
                ('cus_crated_at', models.DateTimeField(auto_now_add=True)),
                ('cus_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='redeemTbl',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('Ccode', models.CharField(max_length=50, unique=True)),
                ('upi_address', models.CharField(max_length=30)),
                ('review', models.TextField(null=True)),
                ('cus_crated_at', models.DateTimeField(auto_now_add=True)),
                ('cus_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
